DROP TABLE SALARY_STEPS;

CREATE TABLE SALARY_STEPS 
(
  ID NUMBER NOT NULL 
, SALARY NUMBER NOT NULL 
, DESCRIPTION VARCHAR2(255 BYTE) 
, CONSTRAINT SALARY_STEPS_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SALARY_STEPS_PK ON SALARY_STEPS (ID ASC) 
  )
  ENABLE 
) 


